[package]
name = "syan-haskell"
description = "Haskell AST definitions and parser implementation using syan"
version = "0.1.0"
edition = "2021"
authors = ["Yasuo Ozu <yasuo@ozu.email>"]
repository = "https://github.com/yasuo-ozu/syan"
keywords = ["haskell", "ast", "parser", "proc-macro", "parsing"]
categories = [
  "data-structures",
  "parser-implementations",
]
license = "MIT"

[dependencies]
syan = { path = "../core" }
syan-macro = { path = "../macro" }
proc-macro2 = "1.0"
quote = "1.0"

[[test]]
name = "integration"
path = "tests/integration.rs"