[package]
name = "syan"
description = "Syntactic and structural parser fundamentals, reimplementing syn crate"
version = "0.1.0"
edition = "2021"
authors = ["Yasuo Ozu <yasuo@ozu.email>"]
repository = "https://github.com/yasuo-ozu/syan"
keywords = ["macros", "syn", "parser", "proc-macro", "parsing"]
categories = [
  "data-structures",
  "no-std::no-alloc",
  "rust-patterns",
  "parser-implementations",
]
license = "MIT"

[dependencies]
parametrized = "0.1.7"
