[package]
name = "syan"
description = "Syntactic and structural parser fundamentals, reimplementing syn crate"
version = "0.1.0"
edition = "2021"
authors = ["Yasuo Ozu <yasuo@ozu.email>"]
repository = "https://github.com/yasuo-ozu/syan"
keywords = ["macros", "syn", "parser", "proc-macro", "parsing"]
categories = [
  "data-structures",
  "no-std::no-alloc",
  "rust-patterns",
  "parser-implementations",
]
license = "MIT"

[dependencies]
parametrized = "0.1.7"
newer-type = "0.1.1"
proc-macro2 = { version = "1.0", optional = true }
syan-macro = { path = "../macro", version = "0.1.0" }
decycle = "0.5.1"

[dev-dependencies]
template-quote = "0.4"
type-macro-derive-tricks = "0.2"
trybuild = { version = "1.0", features = ["diff"] }

[features]
default = ["proc_macro2"]
proc_macro2 = ["dep:proc-macro2"]
